config/routes.rb
Rails.application.routes.draw do

    get '/' => 'site#home' 

    resources :projects do 
      resources :entries 
    end 
end

app/models/entry.rb
class Entry < ActiveRecord::Base

	belongs_to :project
	validates :hours, {numericality: true}
	validates :minutes, {numericality: true}
	validates :date, presence: true
	validates :hours, presence: true
	validates :minutes, presence: true
	validates_associated :project

	



end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :entries
	validates :name, {uniqueness: true, presence: true, length: {maximum: 30}, format: {with: /\w/}}
	
	def self.iron_find(id)
		where(id: id).first
	end

	def self.clean_old(time)
		# where(update_at: id.)
		to_kill = where("updated_at < ?", time)
		to_kill.destroy_all
	end

	def self.last_created_projects(n)
		order(created_at: :desc).limit(n)
	end

	def monthly_work(month,year)
		date = DateTime.new(year, month)
		es = entries.where(date: date.beginning_of_month..date.end_of_month)
		hours = 0
		minutes = 0
		es.each do |entry| 
			hours += entry.hours
			minutes += entry.minutes
		end
		minutes/60 + hours
	end 
end


  		

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
		@date = DateTime.now
		@project = Project.find params[:project_id]
		# @entries = @project.monthly_work(current_month) 
		@entries = @project.entries.where(date: @date.beginning_of_month..@date.end_of_month)
	end



	def new
		@project = Project.find params[:project_id]
		@entry = @project.entries.new
	end

	def create 
		@project = Project.find params[:project_id]
		@entry = @project.entries.new entry_params

		if @entry.save
			flash[:notice] = "Entry created successfully"
			redirect_to action:  'index', controller: 'entries', project_id: @project.id 
		else 
			flash[:error] = "Something went wrong"
			render 'new'
		end 
	end 

	def edit
		@project = Project.find params[:project_id]
		@entry = @project.entries.find params[:id]

	end

	def update 
		@project = Project.find params[:project_id]
		@entry = @project.entries.find params[:id]

		if @entry.update_attributes(entry_params)
			UserMailer.entry_created(@project).deliver
			redirect_to action:  'index', controller: 'entries', project_id: @project.id
		else 
			render 'edit'

		end
	end

	def destroy
		@project = Project.find params[:project_id]
		@entry = @project.entries.find params[:id]

		if @entry.destroy
			redirect_to action: 'index', controller: 'entries', project_id: @project.id
		end

	end

	private 

	def entry_params
		params.require(:entry).permit(:hours, :minutes, :date)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  	@projects = Project.last_created_projects(9)
  	if @projects.empty? 
  		render 'no_projects_found'
  	end
  end

  def show
  	unless @projects = Project.find_by(id: params[:id])
  		render 'no_projects_found', layout: 'error'
  	end 
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home 
		 
	end

	def contact
		 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/entries/_form.html.erb
<%= form_for [@project, @entry] do |f|%>
	<%= f.label :hours %>
	<%= f.text_field :hours, size: 4 %>
	<br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes, size: 4 %>
	<br>
	<%= f.label :date %>
	<%= f.date_field :date, size: 4 %>
	<br>
	
	<%= f.submit 'Save' %>
	<%= link_to 'Cancel', project_entries_path(@project)%>

<%end%>

<% if @entry.errors.any? %>
	<ul>
		<% @entry.errors.full_messages.each do |error_msg|%>
			<li><%= error_msg%></li>
		<%end%>
	</ul>
<%end%>

app/views/entries/edit.html.erb
<h2>Edit an existing entry in <%= @project.name%> project</h2>
<%= render 'form'%>

app/views/entries/index.html.erb
<%if flash[:notice]%>
	<%= flash[:notice]%>
<%end%>



<h1><%= @project.name%></h1>
<ul>
	<%@entries.each do |entry|%>
			<li>
				<%=entry.hours%> h
				<%=entry.minutes%> m -
				<%=entry.date%> -
				<%= link_to('edit', edit_project_entry_path(@project, entry))%>
				<%= link_to('Delete', project_entry_path(@project, entry),
				method: :delete, data: {confirm: 'Are you sure?'})%>
			</li>

		
	<%end%>
	<p>Total hours worked: <%= @project.monthly_work(@date.month, @date.year)%></p>
</ul>
<%= link_to('projects', projects_path)%>
<br>
<%= link_to('Create Entry', new_project_entry_path(@project.id))%>

app/views/entries/new.html.erb
<%if flash[:error]%>
	<%= flash[:error]%>
<%end%>
<br>
<br>


<h2>Creating a new entry in <%= @project.name%> project</h2>
<%= render 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color:red;">

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<h1>Projects#index</h1>


<ul>
	<% @projects.each do |project| %>
		<li><%= link_to(project.name, project_entries_path(project))%>
			<% if project.description.present?%> 
				- <%=project.description%>
			<%end%>
		</li>		
	<%end%>
	
</ul>

app/views/projects/show.html.erb
<h1>Selected Project</h1>

<h2><%="called #{@projects.name} - #{@projects.description}"%></h2>

app/views/site/contact.html.erb
<h1>Contact Us</h1>

<a href="#">contact@example</a>

app/views/site/home.html.erb
<h1>Welcome to this timetracking tool</h1>

<p>Ironhack powered</p>